services:
  orchestrator-library-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator-library-ui
    ports:
      - '80:80'
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
