version: '3.8'

services:
  orchestrator-library-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator-library-ui
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s