apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "orchestrator-library-ui.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "orchestrator-library-ui.name" . }}
    spec:
      containers:
        - name: orchestrator-library-ui
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 80